"""
Shared state definitions for the LangGraph multi-agent pipeline.

AgentState is the TypedDict that flows through all nodes in the graph.
Each node reads from and writes to this shared state.

UC-012: Refactored to multi-agent parallel architecture.
  - Added: factor_results, suggestion_results, harm_results, errors
    (all use Annotated[list, operator.add] for fan-in from parallel sub-agents)
  - Removed: rag_context (replaced by per-agent result fields)

UC-015: Introduced explicit per-agent state types (FactorState, HarmState,
  SuggestionState) and their corresponding output states. Agents now use their
  dedicated *_task key to generate sub-queries via LLM before tool retrieval.
"""

from __future__ import annotations

import operator
from enum import Enum
from typing import Annotated, Any, List, Optional

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


class SafetyCategory(str, Enum):
    """Classification of question safety level by Triage Agent."""

    SAFE = "SAFE"
    PRESCRIPTION = "PRESCRIPTION"
    DIAGNOSIS = "DIAGNOSIS"
    EMERGENCY = "EMERGENCY"


# ---------------------------------------------------------------------------
# Per-agent internal state types (UC-015)
# These describe the internal working state of each sub-agent node.
# ---------------------------------------------------------------------------

class FactorState(TypedDict):
    """Internal working state for the Factor Agent node."""

    rag_sources: dict
    web_sources: dict
    factor_task: str       # Specialized task assigned by Supervisor
    queries: List[str]     # Sub-queries generated by LLM
    factor_context: dict   # Aggregated context from tools
    messageId: str


class FactorOutputState(TypedDict):
    """Output written back to AgentState by the Factor Agent."""

    factor_context: dict   # Contains: factor_summary (str), sources (list)


class HarmState(TypedDict):
    """Internal working state for the Harm Agent node."""

    rag_sources: dict
    web_sources: dict
    harm_task: str         # Specialized task assigned by Supervisor
    queries: List[str]     # Sub-queries generated by LLM
    harm_context: dict     # Aggregated context from tools
    messageId: str


class HarmOutputState(TypedDict):
    """Output written back to AgentState by the Harm Agent."""

    harm_context: dict     # Contains: harm_summary (str)


class SuggestionState(TypedDict):
    """Internal working state for the Suggestion Agent node."""

    rag_sources: dict
    web_sources: dict
    suggestion_task: str   # Specialized task assigned by Supervisor
    queries: List[str]     # Sub-queries generated by LLM
    suggestion_context: dict  # Aggregated context from tools
    messageId: str


class SuggestionOutputState(TypedDict):
    """Output written back to AgentState by the Suggestion Agent."""

    suggestion_context: dict  # Contains: suggestion_summary (str), sources (list)


# ---------------------------------------------------------------------------
# Shared pipeline state
# ---------------------------------------------------------------------------

class AgentState(MessagesState):
    """
    Shared state for the LangGraph multi-agent pipeline (UC-015).

    Extends MessagesState to get the built-in `messages` field with
    proper message accumulation. Additional fields track the pipeline's
    progress through triage, parallel sub-agents, and response generation.

    Fan-in fields (Annotated with operator.add):
        factor_results, suggestion_results, harm_results, errors
        — Multiple parallel nodes append to these lists without overwriting.
    """

    # --- Input / Context ---
    user_input: str          # Original question from the user
    chat_history: List[Any]  # Trimmed history for LLM prompt injection (populated by pipeline)

    # --- Triage Agent output ---
    is_safe: bool                  # Whether the question passed safety check
    triage_results: SafetyCategory  # Safety classification result

    # --- Supervisor output ---
    intent: str             # "SMALL_TALK" | "DIABETES" — set by supervisor_node
    follow_up_question: str
    should_response: bool
    small_talk_reply: str   # Pre-generated reply from supervisor LLM when intent == SMALL_TALK

    # --- Sub-Agent Tasks (set by Supervisor, consumed by each agent) ---
    factor_task: str       # Specialized task for factor_agent
    suggestion_task: str   # Specialized task for suggestion_agent
    harm_task: str         # Specialized task for harm_agent

    # --- Sub-Agent Reducer Outputs (UC-015: fan-in via operator.add reducer) ---
    factor_results: Annotated[List[dict], operator.add]
    # Written by: factor_agent_node
    # Format: [{"factor_summary": str, "sources": list[dict]}]

    suggestion_results: Annotated[List[dict], operator.add]
    # Written by: suggestion_agent_node
    # Format: [{"suggestion_summary": str, "sources": list[dict]}]

    harm_results: Annotated[List[dict], operator.add]
    # Written by: harm_agent_node
    # Format: [{"harm_summary": str}]

    # --- Error accumulation (fan-in, per-node errors don't stop flow) ---
    errors: Annotated[List[str], operator.add]
    # Each node appends error strings; Response Agent surfaces them if needed.

    # --- Response output ---
    response_context: dict  # Final answer and metadata from response agent

    # --- Metadata ---
    messageId: str  # Message identifier for tracking
    nodes_visited: Annotated[List[str], operator.add]  # Accumulate visited node names
